baseURL = "https://1462822001-sudo.github.io/"
languageCode = 'en-us'
title = 'My Blog'
theme = "PaperMod"

[params]
BookSection = "posts"
ShowReadingTime = true
ShowPostNavLinks = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true

[menu]
[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 2